### ISSUE TITLE
feat: easier navigation in the board

### ISSUE THREAD

**Issue by Davidyz** [jim-fx/sudoku.nvim#10]
In the current version the arrow keys (or hjkl) move the cursor by one character at a time. This means that to move from one sudoku cell to a neighboring cell requires at least 2 key presses (4 if the cell is in a different 3x3 block). It would be nice if the keys can be remapped so that when the cursor is in the board the cursor can be moved to the neighboring sudoku cell by one single key press.

Extra options for navigating between the 3x3 blocks would also be nice.

**Comment by jim-fx** [comment]
Hi @Davidyz :) 
Thanks for trying this out, just saw this issue, you could use `4j` / `4k` to move a square up and down and `8j` / `8l` to move horizontally, I am going to add a tip to the README
